# Generated by Django 4.1 on 2022-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posistion',
            field=models.CharField(default='', max_length=50, verbose_name='position'),
        ),
    ]
