# Generated by Django 4.1 on 2022-09-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_posistion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='posistion',
            new_name='position',
        ),
    ]
