# Generated by Django 4.1 on 2022-09-14 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_rename_posistion_profile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('notif_for', models.CharField(max_length=50, verbose_name='notif_for')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='date_created')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
