# Generated by Django 4.1 on 2022-09-14 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_noification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noification',
            new_name='Notification',
        ),
    ]
