# Generated by Django 4.1 on 2022-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_noification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sched_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sched_url'),
        ),
    ]
