# Generated by Django 4.1 on 2022-09-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sched_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50, verbose_name='course')),
                ('year_level', models.CharField(max_length=50, verbose_name='year_level')),
                ('section', models.CharField(max_length=50, verbose_name='section')),
                ('class_list', models.FileField(upload_to='student/excel', verbose_name='students')),
                ('date_request', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=50, verbose_name='student_no')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='middle_name')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('contact', models.CharField(max_length=20, verbose_name='contact')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.sched_request')),
            ],
        ),
    ]
