# Generated by Django 4.1 on 2022-09-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentListExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.FileField(upload_to='student/excel', verbose_name='students')),
            ],
        ),
    ]
