# Generated by Django 4.1 on 2022-09-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sched_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default='Pending', max_length=50, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Rejected_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.sched_request', verbose_name='sched')),
            ],
        ),
        migrations.CreateModel(
            name='Approved_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.sched_request', verbose_name='sched')),
            ],
        ),
    ]
