# Generated by Django 4.1 on 2022-09-09 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_sched_request_status_rejected_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_schedule',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejected_schedule',
            name='rejected_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sched_request',
            name='status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='status'),
        ),
    ]
