# Generated by Django 4.1 on 2022-09-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_approved_schedule_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sched_Time_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(auto_now_add=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sched', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.approved_schedule', verbose_name='sched')),
            ],
        ),
    ]
