# Generated by Django 4.1 on 2022-09-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_approved_schedule_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_schedule',
            name='sched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.sched_request', verbose_name='sched'),
        ),
        migrations.AlterField(
            model_name='rejected_schedule',
            name='sched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.sched_request', verbose_name='sched'),
        ),
        migrations.AlterField(
            model_name='sched_time_usage',
            name='sched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.approved_schedule', verbose_name='sched'),
        ),
    ]
