# Generated by Django 4.1 on 2022-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_approved_schedule_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sched_request',
            name='notif_status',
            field=models.CharField(default='unread', max_length=50, verbose_name='notif_status'),
        ),
    ]
