# Generated by Django 4.1 on 2022-09-19 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_approved_schedule_sched_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approved_schedule',
            options={'ordering': ('-date_approved',)},
        ),
        migrations.AlterModelOptions(
            name='rejected_schedule',
            options={'ordering': ('-date_approved',)},
        ),
        migrations.AlterModelOptions(
            name='sched_request',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='sched_time_usage',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='approved_schedule',
            name='sched',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.sched_request', verbose_name='sched'),
        ),
        migrations.AlterField(
            model_name='rejected_schedule',
            name='sched',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.sched_request', verbose_name='sched'),
        ),
        migrations.AlterField(
            model_name='sched_time_usage',
            name='sched',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.approved_schedule', verbose_name='sched'),
        ),
    ]
