# Generated by Django 4.1 on 2022-09-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_approved_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sched_time_usage',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
