# Generated by Django 4.1 on 2022-10-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_sched_time_usage_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='sched_request',
            name='comlab_room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='comlab_room'),
        ),
    ]
