# Generated by Django 4.1 on 2022-10-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_sched_request_comlab_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='room')),
                ('floor', models.CharField(max_length=50, verbose_name='floor')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
