# Generated by Django 4.1 on 2022-10-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_computer_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sched_request',
            name='comlab_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comlab_room', to='transaction.computer_lab'),
        ),
    ]
