# Generated by Django 4.1 on 2022-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_sched_request_comlab_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_lab',
            name='room',
            field=models.CharField(max_length=50, unique=True, verbose_name='room'),
        ),
    ]
