# Generated by Django 4.1 on 2022-10-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_computer_lab_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_lab',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='status'),
        ),
    ]
