# Generated by Django 4.1 on 2022-10-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_computer_lab_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_lab',
            name='status',
            field=models.CharField(blank=True, default='Available', max_length=50, null=True, verbose_name='status'),
        ),
    ]
